spring:
  datasource:
    url: jdbc:h2:mem:auth_db
    driver-class-name: org.h2.Driver
    # External Libraries -> Maver:com.h2database -> org.h2.Driver 설정해준다
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  h2:
    console:
      enabled: true
      path: /h2-console
